=== PowerMobileTeam/OpenRTS/example/assets/xsd/units.xsd
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.w3schools.com" xmlns="http://www.w3schools.com"
	elementFormDefault="qualified">
	<xs:complexType name="unitType">
		
		<xs:sequence>
			<xs:element name="UIName">
				<xs:complexType>
					<xs:attribute name="value" type="xs:string"></xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="Race">
				<xs:complexType>
					<xs:attribute name="value" type="xs:string"></xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="Radius">
				<xs:complexType>
					<xs:attribute name="value" type="xs:float"></xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="SeparationRadius">
				<xs:complexType>
					<xs:attribute name="value" type="xs:float"></xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="Speed">
				<xs:complexType>
					<xs:attribute name="value" type="xs:float"></xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="Mass">
				<xs:complexType>
					<xs:attribute name="value" type="xs:float"></xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="ModelPath" minOccurs="0" maxOccurs="1">
				<xs:complexType>
					<xs:attribute name="value" type="xs:string"></xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="MaxHealth">
				<xs:complexType>
					<xs:attribute name="value" type="xs:int"></xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="Sight">
				<xs:complexType>
					<xs:attribute name="value" type="xs:float"></xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="MoverLink">
				<xs:complexType>
					<xs:attribute name="value" type="xs:string"></xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="WeaponList">
				<xs:complexType>
					<xs:attribute name="WeaponLink" type="xs:string"></xs:attribute>
				</xs:complexType>
			</xs:element>
			<xs:element name="ActorLink">
				<xs:complexType>
					<xs:attribute name="value" type="xs:string"></xs:attribute>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="id" type="xs:string"/>
	</xs:complexType>

	<xs:complexType name="catalogType">
		<xs:sequence>
			<xs:element name="Unit" type="unitType" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>

	<xs:element name="catalog" type="catalogType" />
</xs:schema>

=== PowerMobileTeam/OpenRTS/core/assets/data/army/units.xml
<?xml version="1.0" encoding="UTF-8"?>
<catalog xmlns="http://www.w3schools.com" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.w3schools.com ../../xsd/units.xsd">
	<Unit id="Marine">
		<UIName value="Marine Le Pen" />
		<Race value="human" />
		<Radius value="0.25" />
		<SeparationRadius value="0.25" />
		<Speed value="2.5" />
		<Mass value="1" />
		<MaxHealth value="60" />
		<Sight value="7" />
		<MoverLink value="Ground" />
		<WeaponList WeaponLink="Rifle" />
		<ActorLink value="Marine" />
	</Unit>
	<Unit id="humanCruiser">
		<UIName value="Cruiser" />
		<Race value="human" />
		<Radius value="0.6" />
		<SeparationRadius value="0.6" />
		<Speed value="4" />
		<Mass value="2" />
		<MaxHealth value="300" />
		<Sight value="10" />
		<MoverLink value="Fly" />
		<WeaponList WeaponLink="Battery" />
		<ActorLink value="Aircraft" />
	</Unit>
	<Unit id="BigAlien">
		<UIName value="Big alien" />
		<Race value="alien" />
		<Radius value="0.75" />
		<SeparationRadius value="0.75" />
		<Speed value="1.5" />
		<Mass value="1.3" />
		<MaxHealth value="120" />
		<Sight value="10" />
		<MoverLink value="GroundProne" />
		<WeaponList WeaponLink="StdWeapon" />
		<ActorLink value="BigAlien" />
	</Unit>
	<Unit id="SmallAlien">
		<UIName value="Small alien" />
		<Race value="alien" />
		<Radius value="0.35" />
		<SeparationRadius value="0.35" />
		<Speed value="7" />
		<Mass value="0.3" />
		<ModelPath value="alien/infantry01.mesh.xml" />
		<MaxHealth value="120" />
		<Sight value="8" />
		<MoverLink value="Ground" />
		<WeaponList WeaponLink="MeleeWeapon" />
		<ActorLink value="SmallAlien" />
	</Unit>
</catalog>
